export const UserActionTypes = {
  GET_USER_DATA_START: "GET_USER_DATA_START",
  GET_USER_DATA_SUCC: "GET_USER_DATA_SUCC",
  GET_USER_DATA_FAIL: "GET_USER_DATA_FAIL",
};

export const configActionTypes = {
  GET_CONFIG_START: "GET_CONFIG_START",
  GET_CONFIG_SUCC: "GET_CONFIG_SUCC",
  GET_CONFIG_FAIL: "GET_CONFIG_FAIL",
};

export const marketActionTypes = {
  GET_MARKET_START: "GET_MARKET_START",
  GET_MARKET_SUCC: "GET_MARKET_SUCC",
  GET_MARKET_FAIL: "GET_MARKET_FAIL",
};

export const exchangeActionTypes = {
  GET_EXCHANGE_START: "GET_EXCHANGE_START",
  GET_EXCHANGE_SUCC: "GET_EXCHANGE_SUCC",
  GET_EXCHANGE_FAIL: "GET_EXCHANGE_FAIL",
};


export const RESET_STATE = 'RESET_STATE'